# Uncomment this line to define a global platform for your project
platform :ios, '8.1'

target 'SnapMe' do
pod 'MBProgressHUD', '~> 0.9'
pod 'AFNetworking', '~> 2.5'
end

target 'SnapMeTests' do

end

